export const FIND_ALL = 'FIND_ALL';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';